version: '3'
services:
  app: 
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - /app/node_modules
      - ./app:/app

  nginx:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - ./proxy/conf.d:/etc/nginx/conf.d
    depends_on:
     - app
    