version: '3'
services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - /app/node_modules
      - ./app:/app
    env_file: ./.env  
    environment:
      - DB_HOST=mongodb
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=my-test
      - DB_PORT=27017

  mongodb:
    image: mongo
    ports: 
      - "27017:27017"
    env_file: ./.env  
    environment:  
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodata:/data/db
     
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - "8081:8081"
    env_file: ./.env  
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

  nginx:
    image: nginx
    ports:
     - "80:80"
    volumes:
     - ./proxy/conf.d:/etc/nginx/conf.d
    depends_on:
     - app    
   
volumes:
  mongodata:
    driver: local
          